services:
  - type: web
    name: aitm-mom
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables in Render dashboard:
    # MONGODB_URI, JWT_SECRET, EMAIL_USER, EMAIL_PASS
